// players.js


export function players()  { 
  return ([
  {
    id: 1,
    firstName: 'Lionel',
    lastName: 'Messi',
    age: 34,
    club: 'Paris Saint-Germain',
    trophies: ['10 La Liga titles', '4 UEFA Champions League titles', '7 Copa del Rey titles'],
    nationality: 'Argentine',
    bio: 'Lionel Messi, born on June 24, 1987, is an Argentine professional footballer widely considered one of the greatest players of all time...',
    img: 'https://example.com/messi.jpg',
  },
  {
    id: 2,
    firstName: 'Cristiano',
    lastName: 'Ronaldo',
    age: 36,
    club: 'Manchester United',
    trophies: ['3 Premier League titles', '1 UEFA Champions League title', '1 UEFA European Championship'],
    nationality: 'Portuguese',
    bio: 'Cristiano Ronaldo, born on February 5, 1985, is a Portuguese professional footballer known for his goal-scoring prowess and athleticism...',
    img: 'https://example.com/ronaldo.jpg',
  },
  {
    id: 3,
    firstName: 'Neymar',
    lastName: 'Jr',
    age: 29,
    club: 'Paris Saint-Germain',
    trophies: ['3 La Liga titles', '1 UEFA Champions League title', '1 Copa Libertadores title'],
    nationality: 'Brazilian',
    bio: 'Neymar Jr., born on February 5, 1992, is a Brazilian forward renowned for his skillful play and flair on the field...',
    img: 'https://example.com/neymar.jpg',
  },
  {
    id: 4,
    firstName: 'Robert',
    lastName: 'Lewandowski',
    age: 33,
    club: 'Bayern Munich',
    trophies: ['7 Bundesliga titles', '1 UEFA Champions League title', '3 DFB-Pokal titles'],
    nationality: 'Polish',
    bio: 'Robert Lewandowski, born on August 21, 1988, is a Polish striker known for his goal-scoring ability and leadership on the pitch...',
    img: 'https://example.com/lewandowski.jpg',
  },
  {
    id: 5,
    firstName: 'Kylian',
    lastName: 'Mbappé',
    age: 23,
    club: 'Paris Saint-Germain',
    trophies: ['3 Ligue 1 titles', '1 FIFA World Cup'],
    nationality: 'French',
    bio: 'Kylian Mbappé, born on December 20, 1998, is a French forward recognized for his speed, agility, and goal-scoring prowess...',
    img: 'https://example.com/mbappe.jpg',
  },
  {
    id: 6,
    firstName: 'Kevin',
    lastName: 'De Bruyne',
    age: 30,
    club: 'Manchester City',
    trophies: ['4 Premier League titles', '1 FA Cup', '1 EFL Cup'],
    nationality: 'Belgian',
    bio: 'Kevin De Bruyne, born on June 28, 1991, is a Belgian midfielder known for his passing ability, vision, and leadership on the field...',
    img: 'https://example.com/debruyne.jpg',
  },
  {
    id: 7,
    firstName: 'Mohamed',
    lastName: 'Salah',
    age: 29,
    club: 'Liverpool',
    trophies: ['1 Premier League title', '1 UEFA Champions League title', '1 FIFA Club World Cup'],
    nationality: 'Egyptian',
    bio: 'Mohamed Salah, born on June 15, 1992, is an Egyptian forward known for his goal-scoring exploits and contributions to Liverpool...',
    img: 'https://example.com/salah.jpg',
  },
  {
    id: 8,
    firstName: 'Erling',
    lastName: 'Haaland',
    age: 21,
    club: 'Borussia Dortmund',
    trophies: ['1 DFB-Pokal title'],
    nationality: 'Norwegian',
    bio: 'Erling Haaland, born on July 21, 2000, is a Norwegian striker known for his physicality, speed, and clinical finishing...',
    img: 'https://example.com/haaland.jpg',
  },
  {
    id: 9,
    firstName: 'Bruno',
    lastName: 'Fernandes',
    age: 27,
    club: 'Manchester United',
    trophies: ['1 UEFA Europa League title'],
    nationality: 'Portuguese',
    bio: 'Bruno Fernandes, born on September 8, 1994, is a Portuguese midfielder recognized for his creativity and goal-scoring ability...',
    img: 'https://example.com/fernandes.jpg',
  },
  {
    id: 10,
    firstName: 'Harry',
    lastName: 'Kane',
    age: 28,
    club: 'Tottenham Hotspur',
    trophies: ['1 Premier League Golden Boot', '1 FIFA World Cup Golden Boot'],
    nationality: 'English',
    bio: 'Harry Kane, born on July 28, 1993, is an English striker known for his goal-scoring prowess and leadership on and off the field...',
    img: 'https://example.com/kane.jpg',
  },
])}
  

  